version: "1.0"
generated: 2025-08-08T22:11:47.244511+02:00
project:
    name: template-mcp-config
    description: Production-ready MCP configuration template with Context7 integration and comprehensive tooling for modern development workflows
    type: library
    language: javascript
    keywords:
        - mcp
        - model-context-protocol
        - template
        - context7
        - configuration
        - claude
        - ai-tools
        - playwright
        - browser-automation
        - development-tools
        - team-collaboration
    repository:
        url: "https://github.com/LarsArtmann/template-mcp-config"
        owner: "LarsArtmann"
        name: template-mcp-config
        branch: master
    contact:
        name: Community Maintainers
    license:
        type: EUPL-1.2
        file: LICENSE
template:
    type: intermediate
    variant: default
    include_toc: true
    toc_depth: 3
    sections:
        - description
        - features
        - installation
        - usage
        - configuration
        - contributing
        - license
badges:
    enabled: false
    license: false
    version: false
    stars: false
    forks: false
    issues: false
    build_status: false
    style: flat
content:
    development:
        setup:
            - git clone https://github.com/LarsArtmann/template-mcp-config.git
            - cd template-mcp-config
            - cp .mcp.json .mcp.json.local
            - Configure your environment variables in .env
            - Restart your MCP-compatible client (Claude, Cursor, etc.)
    contributing:
        enabled: true
        guidelines:
            - Prioritize zero-configuration servers (no API keys required)
            - Follow the bunx pattern for consistency
            - Update the server table in README.md
            - Test with multiple MCP clients (Claude Desktop, Cursor, VS Code)
            - Include usage examples in your pull request
language_trends:
    enabled: true
    months: 12
    bucket: readme-trends
    update_frequency: weekly
    chart_type: lines
    show_legend: true
    max_languages: 6
github:
    enabled: true
    owner: LarsArtmann
    default_branch: master
    repository: template-mcp-config
    actions:
        enabled: true
automation:
    smart_updates: false
    ignore_timestamp: true
    update_schedule: 0 0 * * 1
    commit_message: 'docs: update README.md [automated]'
    create_pr: false
    pr_title: 'docs: update README.md'
    pr_body: Automated README update generated by template-readme
formatting: {}
