# TypeSpec Configuration for MCP Configuration Validation
# This file configures the TypeSpec compiler and output generation

emit:
  - "@typespec/json-schema"
  - "@typespec/openapi3"

options:
  "@typespec/json-schema":
    emitter-output-dir: "{project-root}/generated/json-schema"
    file-type: yaml
    
  "@typespec/openapi3":
    emitter-output-dir: "{project-root}/generated/openapi"
    file-type: yaml

warn-as-error: false

trace: ["*"]